### ISSUE TITLE
Does this device plugin support kubevirt about GPU?

### ISSUE THREAD

**Issue by larryliuqing** [RadeonOpenCompute/k8s-device-plugin#25]
Hi,

Hi, I have a AMD GPU (FirePro S7150), and I want to kubevirt vm uses the GPU, does kubevirt support AMD GPU ?
**[pass through]**
```
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Tonga XT GL [FirePro S7150] [1002:6929]
	Subsystem: Dell Tonga XT GL [FirePro S7150] [1028:1d35]
	Kernel driver in use: vfio-pci
	Kernel modules: amdgpu
```
**[kubevirt configuration]**
```
  configuration:
    permittedHostDevices:
      pciHostDevices:
      - externalResourceProvider: true
        pciVendorSelector: 1002:6929
        resourceName: amdgpu.com/FirePro_S7150
```
        
**[AMD gpu device plugin]**
`https://github.com/RadeonOpenCompute/k8s-device-plugin`

I can't get the gpu properties from node Capacity, when done the above three steps(also add the GPU feature gates), does here miss something?
